on:
  release:
    types:
      - prereleased
      - released

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Checkout the exact commit tagged on the release.
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.target_commitish }}

      - name: Validate and extract release information
        id: release-info
        uses: manovotny/github-releases-for-automated-package-publishing-action@v2.0.1

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          always-auth: true
          node-version: 'lts/*'
          registry-url: 'https://npm.pkg.github.com'
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: 'Build'
        run: |
          pnpm build

      - name: Publish version
        if: steps.release-info.outputs.tag == ''
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.RELEASE_PAT }}

      - name: Publish tagged version
        if: steps.release-info.outputs.tag != ''
        run: pnpm publish --no-git-checks --tag ${{ steps.release-info.outputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.RELEASE_PAT }}
